### PR TITLE
new type ThreadId added

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Review by sebaszm — COMMENTED** [review]
I think ::thread_id is not in Core:: ?

**Comment by HaseenaSainul** [comment]
> I think ::thread_id is not in Core:: ?

yes it is https://github.com/rdkcentral/ThunderTools/pull/118#pullrequestreview-2280876772 But outside namespace Core

**Review by sebaszm — CHANGES_REQUESTED** [review]
ThreadId is emitted and searched for in Core:: while it's defined in global namespace. :)

**Review by sebaszm — APPROVED** [review]

**Comment by HaseenaSainul** [comment]
There is no permission to update the branch in rdkcentral, so new PR created from fork: https://github.com/rdkcentral/ThunderTools/pull/130.
Hence closing this PR.

**Pull request closed without merging**
